package com.example.analyzer.service;

import com.example.analyzer.model.EmployeeAnalysis;
import com.example.analyzer.repository.EmployeeAnalysisRepository;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;

@Service
public class PdfExportService {

    private final EmployeeAnalysisRepository analysisRepository;

    public PdfExportService(EmployeeAnalysisRepository analysisRepository) {
        this.analysisRepository = analysisRepository;
    }

    public byte[] exportAnalysisReport(Long analysisId) {
        EmployeeAnalysis analysis = analysisRepository.findById(analysisId)
                .orElseThrow(() -> new RuntimeException("Analysis not found"));

        try (PDDocument document = new PDDocument(); ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
            PDPage page = new PDPage();
            document.addPage(page);

            try (PDPageContentStream contentStream = new PDPageContentStream(document, page)) {
                contentStream.beginText();
                contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD), 16);
                contentStream.newLineAtOffset(50, 750);
                contentStream.showText("Skill Gap Analysis Report");
                
                contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 12);
                contentStream.newLineAtOffset(0, -30);
                contentStream.showText("Employee: " + analysis.getEmployee().getName());
                
                contentStream.newLineAtOffset(0, -20);
                contentStream.showText("Role: " + analysis.getJobRole().getTitle());

                contentStream.newLineAtOffset(0, -20);
                contentStream.showText(String.format("Match Percentage: %.1f%%", analysis.getMatchPercentage()));
                
                contentStream.newLineAtOffset(0, -30);
                contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD), 12);
                contentStream.showText("Detected Skills:");
                contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 12);
                contentStream.newLineAtOffset(0, -20);
                String ds = analysis.getDetectedSkills() != null ? analysis.getDetectedSkills() : "[]";
                contentStream.showText(ds.length() > 80 ? ds.substring(0, 80) + "..." : ds);
                
                contentStream.newLineAtOffset(0, -30);
                contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD), 12);
                contentStream.showText("Missing Skills:");
                contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 12);
                contentStream.newLineAtOffset(0, -20);
                String ms = analysis.getMissingSkills() != null ? analysis.getMissingSkills() : "[]";
                contentStream.showText(ms.length() > 80 ? ms.substring(0, 80) + "..." : ms);

                contentStream.newLineAtOffset(0, -40);
                contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_OBLIQUE), 10);
                contentStream.showText("Generated by AI Skill Gap Analyzer | TN AUTO Skills Platform");

                contentStream.endText();
            }

            document.save(baos);
            return baos.toByteArray();
        } catch (IOException e) {
            throw new RuntimeException("Failed to generate PDF", e);
        }
    }
}