package com.example.analyzer.service;

import com.example.analyzer.model.StudentAnalysis;
import com.example.analyzer.repository.StudentAnalysisRepository;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;

@Service
public class PdfExportService {

    private final StudentAnalysisRepository analysisRepository;

    public PdfExportService(StudentAnalysisRepository analysisRepository) {
        this.analysisRepository = analysisRepository;
    }

    public byte[] exportAnalysisReport(Long analysisId) {
        StudentAnalysis analysis = analysisRepository.findById(analysisId)
                .orElseThrow(() -> new RuntimeException("Analysis not found"));

        try (PDDocument document = new PDDocument(); ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
            PDPage page = new PDPage();
            document.addPage(page);

            try (PDPageContentStream contentStream = new PDPageContentStream(document, page)) {
                contentStream.beginText();
                contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD), 16);
                contentStream.newLineAtOffset(50, 750);
                contentStream.showText("Resume Analysis Report");
                
                contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 12);
                contentStream.newLineAtOffset(0, -30);
                contentStream.showText("Student: " + analysis.getStudent().getName());
                
                contentStream.newLineAtOffset(0, -20);
                contentStream.showText("Role: " + analysis.getJobRole().getTitle());

                contentStream.newLineAtOffset(0, -20);
                contentStream.showText(String.format("Match Percentage: %.1f%%", analysis.getMatchPercentage()));
                
                contentStream.newLineAtOffset(0, -30);
                contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD), 12);
                contentStream.showText("Missing Skills:");
                contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 12);
                contentStream.newLineAtOffset(0, -20);
                String ms = analysis.getMissingSkills() != null ? analysis.getMissingSkills() : "[]";
                contentStream.showText(ms.length() > 80 ? ms.substring(0, 80) + "..." : ms);

                contentStream.newLineAtOffset(0, -40);
                contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_OBLIQUE), 10);
                contentStream.showText("Generated by AI Resume Analyzer");

                contentStream.endText();
            }

            document.save(baos);
            return baos.toByteArray();
        } catch (IOException e) {
            throw new RuntimeException("Failed to generate PDF", e);
        }
    }
}